/*
 * cypher_parser.y -- Bison grammar for the read-only Cypher subset.
 *
 * Only reading constructs are supported (MATCH/WHERE/RETURN and friends).
 * Write clauses (CREATE/MERGE/SET/DELETE/...) are intentionally absent, so
 * such statements are rejected as syntax errors.
 */

%code requires {
	#include "ast.h"

	#ifndef YY_TYPEDEF_YY_SCAN_T
	#define YY_TYPEDEF_YY_SCAN_T
	typedef void *yyscan_t;
	#endif
}

%code top {
	#include <stdlib.h>
	#include <string.h>
}

%code {
	/* yylex is generated by Flex (reentrant, bison-bridge). */
	int yylex(YYSTYPE *yylval_param, yyscan_t scanner);
	static void yyerror(yyscan_t scanner, Query **result, char **errmsg,
	                    const char *msg);
}

%define api.pure full
%define parse.error verbose
%param   { yyscan_t scanner }
%parse-param { Query **result } { char **errmsg }

%union {
	char      *str;
	Expr      *expr;
	ExprList  *exprlist;
	NodePat   *node;
	RelPat    *rel;
	Segment   *seg;
	Path      *path;
	PathList  *pathlist;
	StrList   *strlist;
	PropList  *proplist;
	Match     *match;
	ReturnItem *ritem;
	SortItem  *sort;
	Return    *ret;
	int        num;
	VarLen     varlen;
}

%token <str> IDENT BQIDENT STRING INTEGER REAL

%token MATCH WHERE RETURN AS ORDER BY SKIP LIMIT DISTINCT
%token AND OR NOT IN IS NULLTOK TRUETOK FALSETOK
%token STARTS ENDS WITH CONTAINS ASC DESC
%token ARROW_L ARROW_R LE GE NE DOTDOT

%type <match>     match_clause match_list
%type <pathlist>  pattern_list
%type <path>      pattern
%type <node>      node_pattern
%type <rel>       relationship rel_body rel_detail
%type <seg>       path_tail
%type <strlist>   labels labels_opt rel_types rel_types_opt type_list
%type <proplist>  properties properties_opt prop_map
%type <expr>      expr where_opt skip_opt limit_opt primary literal func_call
%type <exprlist>  arg_list
%type <ret>       return_clause
%type <ritem>     return_item return_item_list
%type <sort>      order_opt sort_list sort_item
%type <num>       distinct_opt sort_dir
%type <varlen>    varlen_opt
%type <str>       variable variable_opt label rel_type property_key

%left OR
%left AND
%right NOT
%nonassoc '=' NE '<' '>' LE GE STARTS ENDS CONTAINS IN IS

/*
 * When a parse fails, Bison discards the semantic values still on its stack.
 * Without these destructors those partially built fragments (and the strings
 * the scanner malloc'd) would leak. Each reduction transfers ownership upward
 * (e.g. list tails are linked into their head), so only the live stack symbols
 * are destroyed, each exactly once.
 */
%destructor { free($$); }                <str>
%destructor { ast_free_expr($$); }       <expr>
%destructor { ast_free_exprlist($$); }   <exprlist>
%destructor { ast_free_strlist($$); }    <strlist>
%destructor { ast_free_proplist($$); }   <proplist>
%destructor { ast_free_node($$); }       <node>
%destructor { ast_free_rel($$); }        <rel>
%destructor { ast_free_segment($$); }    <seg>
%destructor { ast_free_path($$); }       <path>
%destructor { ast_free_pathlist($$); }   <pathlist>
%destructor { ast_free_match($$); }      <match>
%destructor { ast_free_return_item($$); } <ritem>
%destructor { ast_free_sort_item($$); }  <sort>
%destructor { ast_free_return($$); }     <ret>

%%

statement
	: match_list return_clause opt_semicolon
		{ *result = ast_query($1, $2); }
	;

opt_semicolon
	: /* empty */
	| ';'
	;

match_list
	: match_clause                 { $$ = $1; }
	| match_clause match_list      { $1->next = $2; $$ = $1; }
	;

match_clause
	: MATCH pattern_list where_opt { $$ = ast_match($2, $3, NULL); }
	;

where_opt
	: /* empty */                  { $$ = NULL; }
	| WHERE expr                   { $$ = $2; }
	;

pattern_list
	: pattern                      { $$ = ast_pathlist($1, NULL); }
	| pattern ',' pattern_list     { $$ = ast_pathlist($1, $3); }
	;

pattern
	: node_pattern path_tail       { $$ = ast_path($1, $2); }
	;

path_tail
	: /* empty */                              { $$ = NULL; }
	| relationship node_pattern path_tail      { $$ = ast_segment($1, $2, $3); }
	;

node_pattern
	: '(' variable_opt labels_opt properties_opt ')'
		{ $$ = ast_node($2, $3, $4); }
	;

relationship
	: '-' rel_body ARROW_R         { $2->dir = REL_RIGHT; $$ = $2; }
	| ARROW_L rel_body '-'         { $2->dir = REL_LEFT;  $$ = $2; }
	| '-' rel_body '-'             { $2->dir = REL_UNDIR; $$ = $2; }
	;

rel_body
	: /* empty */                  { VarLen z = {0}; $$ = ast_rel(NULL, NULL, NULL, REL_UNDIR, z); }
	| '[' rel_detail ']'           { $$ = $2; }
	;

rel_detail
	: variable_opt rel_types_opt varlen_opt properties_opt
		{ $$ = ast_rel($1, $2, $4, REL_UNDIR, $3); }
	;

varlen_opt
	: /* empty */                  { VarLen z = {0}; $$ = z; }
	| '*'                          { VarLen v = {0}; v.present = 1; $$ = v; }
	| '*' INTEGER                  { VarLen v = {0}; v.present = 1; v.has_min = 1; v.min = atoi($2); v.has_max = 1; v.max = v.min; free($2); $$ = v; }
	| '*' INTEGER DOTDOT           { VarLen v = {0}; v.present = 1; v.has_min = 1; v.min = atoi($2); free($2); $$ = v; }
	| '*' DOTDOT INTEGER           { VarLen v = {0}; v.present = 1; v.has_max = 1; v.max = atoi($3); free($3); $$ = v; }
	| '*' INTEGER DOTDOT INTEGER   { VarLen v = {0}; v.present = 1; v.has_min = 1; v.min = atoi($2); v.has_max = 1; v.max = atoi($4); free($2); free($4); $$ = v; }
	| '*' DOTDOT                   { VarLen v = {0}; v.present = 1; $$ = v; }
	;

labels_opt
	: /* empty */                  { $$ = NULL; }
	| labels                       { $$ = $1; }
	;

labels
	: ':' label                    { $$ = ast_strlist($2, NULL); }
	| ':' label labels             { $$ = ast_strlist($2, $3); }
	;

rel_types_opt
	: /* empty */                  { $$ = NULL; }
	| rel_types                    { $$ = $1; }
	;

rel_types
	: ':' type_list                { $$ = $2; }
	;

type_list
	: rel_type                     { $$ = ast_strlist($1, NULL); }
	| rel_type '|' type_list       { $$ = ast_strlist($1, $3); }
	;

properties_opt
	: /* empty */                  { $$ = NULL; }
	| properties                   { $$ = $1; }
	;

properties
	: '{' '}'                      { $$ = NULL; }
	| '{' prop_map '}'             { $$ = $2; }
	;

prop_map
	: property_key ':' expr                 { $$ = ast_proplist($1, $3, NULL); }
	| property_key ':' expr ',' prop_map    { $$ = ast_proplist($1, $3, $5); }
	;

return_clause
	: RETURN distinct_opt '*' order_opt skip_opt limit_opt
		{ $$ = ast_return($2, 1, NULL, $4, $5, $6); }
	| RETURN distinct_opt return_item_list order_opt skip_opt limit_opt
		{ $$ = ast_return($2, 0, $3, $4, $5, $6); }
	;

distinct_opt
	: /* empty */                  { $$ = 0; }
	| DISTINCT                     { $$ = 1; }
	;

return_item_list
	: return_item                          { $$ = $1; }
	| return_item ',' return_item_list     { $1->next = $3; $$ = $1; }
	;

return_item
	: expr                         { $$ = ast_return_item($1, NULL, NULL); }
	| expr AS variable             { $$ = ast_return_item($1, $3, NULL); }
	;

order_opt
	: /* empty */                  { $$ = NULL; }
	| ORDER BY sort_list           { $$ = $3; }
	;

sort_list
	: sort_item                    { $$ = $1; }
	| sort_item ',' sort_list      { $1->next = $3; $$ = $1; }
	;

sort_item
	: expr sort_dir                { $$ = ast_sort_item($1, $2, NULL); }
	;

sort_dir
	: /* empty */                  { $$ = 0; }
	| ASC                          { $$ = 0; }
	| DESC                         { $$ = 1; }
	;

skip_opt
	: /* empty */                  { $$ = NULL; }
	| SKIP expr                    { $$ = $2; }
	;

limit_opt
	: /* empty */                  { $$ = NULL; }
	| LIMIT expr                   { $$ = $2; }
	;

expr
	: expr OR expr                 { $$ = ast_expr_bin(EXPR_OR, $1, $3); }
	| expr AND expr                { $$ = ast_expr_bin(EXPR_AND, $1, $3); }
	| NOT expr                     { $$ = ast_expr_not($2); }
	| expr '=' expr                { $$ = ast_expr_cmp(CMP_EQ, $1, $3); }
	| expr NE expr                 { $$ = ast_expr_cmp(CMP_NE, $1, $3); }
	| expr '<' expr                { $$ = ast_expr_cmp(CMP_LT, $1, $3); }
	| expr '>' expr                { $$ = ast_expr_cmp(CMP_GT, $1, $3); }
	| expr LE expr                 { $$ = ast_expr_cmp(CMP_LE, $1, $3); }
	| expr GE expr                 { $$ = ast_expr_cmp(CMP_GE, $1, $3); }
	| expr STARTS WITH expr %prec STARTS  { $$ = ast_expr_bin(EXPR_STARTS_WITH, $1, $4); }
	| expr ENDS WITH expr %prec ENDS      { $$ = ast_expr_bin(EXPR_ENDS_WITH, $1, $4); }
	| expr CONTAINS expr                  { $$ = ast_expr_bin(EXPR_CONTAINS, $1, $3); }
	| expr IN '[' arg_list ']' %prec IN   { $$ = ast_expr_in($1, $4); }
	| expr IS NULLTOK %prec IS            { $$ = ast_expr_is_null($1, 0); }
	| expr IS NOT NULLTOK %prec IS        { $$ = ast_expr_is_null($1, 1); }
	| primary                      { $$ = $1; }
	;

primary
	: IDENT                        { $$ = ast_expr_variable($1); }
	| IDENT '.' property_key       { $$ = ast_expr_property($1, $3); }
	| func_call                    { $$ = $1; }
	| literal                      { $$ = $1; }
	| '(' expr ')'                 { $$ = $2; }
	;

func_call
	: IDENT '(' ')'                        { $$ = ast_expr_func($1, 0, 0, NULL); }
	| IDENT '(' '*' ')'                    { $$ = ast_expr_func($1, 0, 1, NULL); }
	| IDENT '(' arg_list ')'               { $$ = ast_expr_func($1, 0, 0, $3); }
	| IDENT '(' DISTINCT arg_list ')'      { $$ = ast_expr_func($1, 1, 0, $4); }
	;

arg_list
	: expr                         { $$ = ast_exprlist($1, NULL); }
	| expr ',' arg_list            { $$ = ast_exprlist($1, $3); }
	;

literal
	: INTEGER                      { $$ = ast_expr_lit(LIT_INT, $1, 0); }
	| REAL                         { $$ = ast_expr_lit(LIT_REAL, $1, 0); }
	| STRING                       { $$ = ast_expr_lit(LIT_STRING, $1, 0); }
	| TRUETOK                      { $$ = ast_expr_lit(LIT_BOOL, NULL, 1); }
	| FALSETOK                     { $$ = ast_expr_lit(LIT_BOOL, NULL, 0); }
	| NULLTOK                      { $$ = ast_expr_lit(LIT_NULL, NULL, 0); }
	;

variable_opt
	: /* empty */                  { $$ = NULL; }
	| variable                     { $$ = $1; }
	;

variable     : IDENT              { $$ = $1; } ;
label        : IDENT              { $$ = $1; } | BQIDENT { $$ = $1; } ;
rel_type     : IDENT              { $$ = $1; } | BQIDENT { $$ = $1; } ;
property_key : IDENT              { $$ = $1; } | BQIDENT { $$ = $1; } ;

%%

#include <stdio.h>

static void yyerror(yyscan_t scanner, Query **result, char **errmsg,
                    const char *msg)
{
	(void)scanner;
	(void)result;
	if (errmsg && *errmsg == NULL)
		*errmsg = strdup(msg);
}

/* Flex reentrant entry points (defined in the generated scanner). */
struct yy_buffer_state;
extern int yylex_init(yyscan_t *scanner);
extern int yylex_destroy(yyscan_t scanner);
extern struct yy_buffer_state *yy_scan_string(const char *str, yyscan_t scanner);
extern void yy_delete_buffer(struct yy_buffer_state *b, yyscan_t scanner);

int cypher_parse(const char *text, Query **out, char **errmsg)
{
	yyscan_t scanner;
	Query *result = NULL;

	*out = NULL;
	if (errmsg)
		*errmsg = NULL;

	if (yylex_init(&scanner) != 0) {
		if (errmsg)
			*errmsg = strdup("cannot initialize scanner");
		return 1;
	}

	struct yy_buffer_state *buf = yy_scan_string(text, scanner);
	int rc = yyparse(scanner, &result, errmsg);
	yy_delete_buffer(buf, scanner);
	yylex_destroy(scanner);

	if (rc != 0) {
		if (result)
			ast_free_query(result);
		return rc;
	}

	*out = result;
	return 0;
}
